# Generated by Django 5.0.6 on 2026-04-04 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated Medical Record Number (MRN-0000001).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(db_index=True, max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "phone",
                    models.CharField(
                        help_text="E.164 format preferred: +256700000000", max_length=30
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="National ID / Passport number. Encrypted at rest.",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "allergies",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated allergens. Will be normalised in v2.",
                        null=True,
                    ),
                ),
                (
                    "chronic_conditions",
                    models.TextField(
                        blank=True,
                        help_text="Pre-existing conditions. Will be normalised in v2.",
                        null=True,
                    ),
                ),
                ("is_diabetic", models.BooleanField(default=False)),
                ("is_hypertensive", models.BooleanField(default=False)),
                (
                    "is_hiv_positive",
                    models.BooleanField(
                        default=False,
                        help_text="Sensitive field — access restricted to clinical staff.",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "insurance_number",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = soft-deleted. Never hard-delete patient records.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Staff member who registered this patient.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients_patient",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"], name="idx_patient_name"
                    ),
                    models.Index(fields=["mrn"], name="idx_patient_mrn"),
                    models.Index(fields=["phone"], name="idx_patient_phone"),
                    models.Index(fields=["is_active"], name="idx_patient_active"),
                    models.Index(fields=["created_at"], name="idx_patient_created"),
                ],
            },
        ),
    ]
