# Generated by Django 5.0.6 on 2026-04-04 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(db_index=True, max_length=100)),
                ("phone", models.CharField(max_length=30)),
                ("photo_url", models.URLField(blank=True, null=True)),
                ("specialisation", models.CharField(db_index=True, max_length=100)),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        help_text="Degree(s) e.g. MBChB, MMED Surgery.",
                        max_length=255,
                    ),
                ),
                (
                    "licence_number",
                    models.CharField(
                        help_text="Medical council registration number.",
                        max_length=60,
                        unique=True,
                    ),
                ),
                (
                    "licence_expiry",
                    models.DateField(
                        blank=True,
                        help_text="Alert fires 60 days before expiry.",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("general_medicine", "General Medicine"),
                            ("surgery", "Surgery"),
                            ("paediatrics", "Paediatrics"),
                            ("obstetrics", "Obstetrics & Gynaecology"),
                            ("cardiology", "Cardiology"),
                            ("orthopaedics", "Orthopaedics"),
                            ("dermatology", "Dermatology"),
                            ("neurology", "Neurology"),
                            ("psychiatry", "Psychiatry"),
                            ("radiology", "Radiology"),
                            ("laboratory", "Laboratory / Pathology"),
                            ("pharmacy", "Pharmacy"),
                            ("emergency", "Emergency"),
                            ("icu", "Intensive Care Unit"),
                            ("dental", "Dental"),
                            ("ophthalmology", "Ophthalmology"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("years_experience", models.PositiveSmallIntegerField(default=0)),
                ("bio", models.TextField(blank=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base fee in the hospital's default currency.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_patients_per_day",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Appointment scheduler refuses bookings beyond this limit.",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False = on leave or unavailable; blocks new bookings.",
                    ),
                ),
                ("accepts_walk_in", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Must be a User with role=doctor.",
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctors_doctor",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "doctors_availability",
                "ordering": ["weekday", "start_time"],
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["department", "is_available"], name="idx_doctor_dept_avail"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["specialisation"], name="idx_doctor_spec"),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(fields=["licence_number"], name="idx_doctor_licence"),
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailability",
            unique_together={("doctor", "weekday", "start_time")},
        ),
    ]
