#!/usr/bin/env bash
# =============================================================================
# HMS Server Setup Script
# Run as root on a fresh Ubuntu 22.04 LTS server.
# Usage: bash setup_server.sh yourdomain.com your@email.com
# =============================================================================
set -euo pipefail

DOMAIN="${1:?Usage: $0 <domain> <email>}"
EMAIL="${2:?Usage: $0 <domain> <email>}"
APP_USER="hms"
APP_DIR="/var/www/hms"
LOG_DIR="/var/log/hms"
ENV_DIR="/etc/hms"

echo "=== [1/9] System update ==="
apt-get update -q
apt-get upgrade -y -q
apt-get install -y -q \
    build-essential curl git wget \
    python3.11 python3.11-venv python3.11-dev \
    postgresql postgresql-contrib \
    redis-server \
    nginx certbot python3-certbot-nginx \
    libpq-dev \
    logrotate \
    fail2ban \
    ufw \
    htop jq

echo "=== [2/9] Create system user ==="
if ! id "$APP_USER" &>/dev/null; then
    useradd --system --home "$APP_DIR" --shell /bin/bash "$APP_USER"
fi

echo "=== [3/9] Create directories ==="
mkdir -p "$APP_DIR" "$LOG_DIR" "$ENV_DIR" /run/hms
chown -R "$APP_USER:$APP_USER" "$APP_DIR" "$LOG_DIR" /run/hms
chmod 750 "$ENV_DIR"
chmod 700 "$LOG_DIR"

# tmpfiles.d so /run/hms persists across reboots
cat > /etc/tmpfiles.d/hms.conf << TMPEOF
d /run/hms 0750 $APP_USER $APP_USER -
TMPEOF

echo "=== [4/9] PostgreSQL setup ==="
systemctl enable --now postgresql

# Create DB user and database
sudo -u postgres psql << SQLEOF
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'hms_user') THEN
    CREATE USER hms_user WITH PASSWORD 'CHANGE_THIS_PASSWORD';
  END IF;
END
\$\$;

CREATE DATABASE hms_db OWNER hms_user;
GRANT ALL PRIVILEGES ON DATABASE hms_db TO hms_user;

-- Revoke dangerous permissions from the application user
-- (done again after migration for audit_auditlog specifically)
\connect hms_db
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CREATE ON SCHEMA public TO hms_user;
SQLEOF

# PostgreSQL performance tuning (adjust for your RAM)
TOTAL_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')
SHARED_BUFFERS=$(( TOTAL_RAM_MB / 4 ))MB
EFFECTIVE_CACHE=$(( TOTAL_RAM_MB * 3 / 4 ))MB

cat >> /etc/postgresql/14/main/postgresql.conf << PGEOF

# HMS tuning — generated by setup_server.sh
shared_buffers = $SHARED_BUFFERS
effective_cache_size = $EFFECTIVE_CACHE
work_mem = 4MB
maintenance_work_mem = 64MB
max_connections = 100
wal_level = replica
archive_mode = on
archive_command = 'cp %p /var/backups/hms/wal/%f'
wal_compression = on
checkpoint_completion_target = 0.9
log_min_duration_statement = 1000
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
PGEOF

systemctl restart postgresql

echo "=== [5/9] Redis security ==="
# Bind Redis to localhost only and require a password
REDIS_PASSWORD=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
cat >> /etc/redis/redis.conf << REDISEOF

# HMS security settings
bind 127.0.0.1 ::1
requirepass $REDIS_PASSWORD
maxmemory 256mb
maxmemory-policy allkeys-lru
REDISEOF

echo "Redis password set to: $REDIS_PASSWORD"
echo "Add this to /etc/hms/.env as: REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379/0"
systemctl restart redis-server

echo "=== [6/9] Firewall setup ==="
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 'Nginx Full'
ufw --force enable

echo "=== [7/9] Fail2ban ==="
cat > /etc/fail2ban/jail.local << F2BEOF
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port    = ssh
filter  = sshd
logpath = /var/log/auth.log

[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
logpath  = /var/log/nginx/hms_error.log
maxretry = 3

[nginx-limit-req]
enabled  = true
filter   = nginx-limit-req
logpath  = /var/log/nginx/hms_error.log
maxretry = 10
F2BEOF

systemctl enable --now fail2ban

echo "=== [8/9] Log rotation ==="
cat > /etc/logrotate.d/hms << LREOF
/var/log/hms/*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    sharedscripts
    postrotate
        systemctl kill -s USR1 hms-gunicorn.service 2>/dev/null || true
    endscript
}

/var/log/nginx/hms_*.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    sharedscripts
    postrotate
        nginx -s reopen 2>/dev/null || true
    endscript
}
LREOF

echo "=== [9/9] Summary ==="
echo ""
echo "✅ Server setup complete."
echo ""
echo "Next steps:"
echo "  1. Deploy the application:  bash deploy.sh"
echo "  2. Set up TLS:              certbot --nginx -d $DOMAIN -d www.$DOMAIN --email $EMAIL --agree-tos --redirect"
echo "  3. Configure /etc/hms/.env  with your actual secrets"
echo "  4. Run migrations:          sudo -u hms /var/www/hms/venv/bin/python manage.py migrate"
