# Generated by Django 5.0.6 on 2026-04-04 21:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, help_text="Brand name.", max_length=200
                    ),
                ),
                (
                    "generic_name",
                    models.CharField(
                        db_index=True, help_text="INN / generic name.", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("antibiotic", "Antibiotic"),
                            ("analgesic", "Analgesic / Pain Relief"),
                            ("antihypertensive", "Antihypertensive"),
                            ("antidiabetic", "Antidiabetic"),
                            ("antiparasitic", "Antiparasitic / Antimalarial"),
                            ("antifungal", "Antifungal"),
                            ("antiretroviral", "Antiretroviral (ARV)"),
                            ("vitamin", "Vitamin / Supplement"),
                            ("vaccine", "Vaccine"),
                            ("anaesthetic", "Anaesthetic"),
                            ("cardiovascular", "Cardiovascular"),
                            ("gastrointestinal", "Gastrointestinal"),
                            ("respiratory", "Respiratory"),
                            ("hormonal", "Hormonal / Contraceptive"),
                            ("dermatological", "Dermatological"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("ml", "ml (liquid)"),
                            ("mg", "mg (injectable)"),
                            ("vial", "Vial"),
                            ("sachet", "Sachet"),
                            ("tube", "Tube"),
                            ("patch", "Patch"),
                            ("inhaler", "Inhaler"),
                            ("suppository", "Suppository"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True, help_text="e.g. 500mg, 250mg/5ml.", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current stock. Updated atomically by dispense().",
                    ),
                ),
                (
                    "reorder_level",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Low-stock alert fires when stock_quantity <= this value.",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit in the hospital's default currency.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=60, null=True, unique=True),
                ),
                (
                    "requires_prescription",
                    models.BooleanField(
                        default=True,
                        help_text="OTC drugs (False) can be dispensed without a prescription.",
                    ),
                ),
                (
                    "controlled_drug",
                    models.BooleanField(
                        default=False,
                        help_text="Schedule I–V controlled substance — requires extra audit steps.",
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("batch_number", models.CharField(blank=True, max_length=60)),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("supplier", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drug",
                "verbose_name_plural": "Drugs",
                "db_table": "pharmacy_drug",
                "ordering": ["generic_name", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"], name="idx_drug_cat_active"
                    ),
                    models.Index(fields=["expiry_date"], name="idx_drug_expiry"),
                    models.Index(fields=["stock_quantity"], name="idx_drug_stock"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dosage", models.CharField(help_text="e.g. 500mg.", max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g. twice daily, every 8 hours.", max_length=60
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveSmallIntegerField(
                        help_text="Number of days to take the medication."
                    ),
                ),
                (
                    "quantity_prescribed",
                    models.PositiveSmallIntegerField(
                        help_text="Total units to dispense."
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Patient instructions: take with food, avoid alcohol, refrigerate, etc.",
                    ),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        help_text="Route of administration: oral, IV, IM, topical, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispensed", "Dispensed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "prescribed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date after which this prescription can no longer be filled.",
                        null=True,
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nurse or admin who dispensed the medication.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        help_text="PROTECT — historical prescriptions must not break if drug is deactivated.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="pharmacy.drug",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="EHR note this prescription was written in.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="records.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "pharmacy_prescription",
                "ordering": ["-prescribed_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"], name="idx_rx_patient_status"
                    ),
                    models.Index(
                        fields=["doctor", "prescribed_at"], name="idx_rx_doctor_ts"
                    ),
                    models.Index(fields=["drug", "status"], name="idx_rx_drug_status"),
                ],
            },
        ),
    ]
