# Generated by Django 5.0.6 on 2026-04-04 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (15, "15 min"),
                            (30, "30 min"),
                            (45, "45 min"),
                            (60, "1 hour"),
                            (90, "1 h 30 min"),
                            (120, "2 hours"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("booked", "Booked"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="booked",
                        max_length=20,
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow Up"),
                            ("procedure", "Procedure"),
                            ("emergency", "Emergency"),
                            ("telehealth", "Telehealth"),
                        ],
                        default="consultation",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="1=emergency, 2=urgent, 3=routine, 4=elective.",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True,
                        help_text="What the patient is coming for (entered at booking).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Receptionist/admin notes."),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Receptionist or admin who booked the slot.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booked_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="PROTECT — cannot delete a patient who has appointments.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments_appointment",
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "scheduled_at"], name="idx_appt_doctor_time"
                    ),
                    models.Index(
                        fields=["patient", "status"], name="idx_appt_patient_status"
                    ),
                    models.Index(
                        fields=["scheduled_at", "status"], name="idx_appt_time_status"
                    ),
                    models.Index(fields=["status"], name="idx_appt_status"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["booked", "checked_in", "in_progress"])
                ),
                fields=("doctor", "scheduled_at"),
                name="unique_active_doctor_slot",
            ),
        ),
    ]
