# Generated by Django 5.0.6 on 2026-04-04 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subjective",
                    models.TextField(
                        blank=True,
                        help_text="Patient-reported: chief complaint, symptom history, pain scale.",
                        null=True,
                    ),
                ),
                (
                    "objective",
                    models.TextField(
                        blank=True,
                        help_text="Clinician findings: physical exam, observations.",
                        null=True,
                    ),
                ),
                (
                    "assessment",
                    models.TextField(
                        blank=True,
                        help_text="Diagnosis and clinical reasoning.",
                        null=True,
                    ),
                ),
                (
                    "plan",
                    models.TextField(
                        blank=True,
                        help_text="Treatment plan: medications, investigations, referrals, follow-up date.",
                        null=True,
                    ),
                ),
                (
                    "icd10_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary ICD-10 diagnosis code e.g. J06.9 (URTI).",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "icd10_description",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label pulled from ICD-10 lookup at save time.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "secondary_diagnoses",
                    models.JSONField(
                        blank=True,
                        help_text="Array of {code, description} for co-morbidities.",
                        null=True,
                    ),
                ),
                (
                    "vitals",
                    models.JSONField(
                        blank=True,
                        help_text="Structured vitals. Schema varies by ward — serializer validates keys.",
                        null=True,
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        help_text="Array of S3 file references. No binary data stored in DB.",
                        null=True,
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the doctor wants to see the patient again.",
                        null=True,
                    ),
                ),
                (
                    "referral_to",
                    models.CharField(
                        blank=True,
                        help_text="Department or specialist the patient is referred to.",
                        max_length=200,
                    ),
                ),
                ("referral_notes", models.TextField(blank=True)),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Set True 24h after creation by Celery. Prevents any further edits.",
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        help_text="The encounter this record documents. May be null for legacy imports.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_record",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="SET NULL — record survives if a doctor leaves the system.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_records",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="PROTECT — records must outlive patient soft-deletion.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "records_medicalrecord",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "recorded_at"], name="idx_record_patient_ts"
                    ),
                    models.Index(
                        fields=["doctor", "recorded_at"], name="idx_record_doctor_ts"
                    ),
                    models.Index(fields=["icd10_code"], name="idx_record_icd10"),
                    models.Index(fields=["is_locked"], name="idx_record_locked"),
                ],
            },
        ),
    ]
